"""Heuristic estimate of % of source lines attributable to LLM-assisted commits or headers."""

from __future__ import annotations

import os
import re
from pathlib import Path

from ..tools import have, run
from .base import Collector

_SKIP_DIRS = {".git", "node_modules", ".venv", "venv", "vendor", "dist", "build",
              "__pycache__", "site-packages", ".mypy_cache", ".pytest_cache"}
_SOURCE_EXTS = {
    ".py", ".js", ".ts", ".tsx", ".jsx", ".go", ".java", ".rb", ".rs",
    ".c", ".cpp", ".h", ".hpp", ".cs", ".php", ".swift", ".kt", ".scala",
}

_AI_COMMIT = re.compile(
    r"(?i)(co-authored-by:.*\b(cursor|copilot|chatgpt|openai|claude|anthropic|"
    r"github-copilot|aider|codeium|tabnine)\b|"
    r"generated with (copilot|chatgpt|claude|cursor)|"
    r"\bai[- ]?(assisted|generated)\b)",
)
_AI_HEADER = re.compile(
    r"(?i)(generated by (chatgpt|copilot|claude|cursor|openai)|"
    r"this (file|code) was (generated|written) by (an )?ai|"
    r"@generated by (chatgpt|copilot|claude|cursor))",
)


class LlmAttributionCollector(Collector):
    name = "llm_attribution"

    def collect(self) -> dict[str, object]:
        file_total = file_ai = 0
        commit_total = commit_ai = 0

        for repo in self.repos:
            src, ai = self._scan_files(repo.path)
            file_total += src
            file_ai += ai
            c_src, c_ai = self._scan_commits(repo.path)
            commit_total += c_src
            commit_ai += c_ai

        if file_ai > 0 and file_total > 0:
            pct = round(file_ai / file_total, 4)
            source = "file headers"
        elif commit_ai > 0 and commit_total > 0:
            pct = round(commit_ai / commit_total, 4)
            source = "git commit attribution"
        else:
            return {"llm_written_pct": 0.0}

        self.warnings.append(
            f"[{self.name}] heuristic estimate from {source}; override via --meta if needed"
        )
        return {"llm_written_pct": min(pct, 1.0)}

    def _scan_files(self, root: Path) -> tuple[int, int]:
        total = ai = 0
        for path in _walk(root):
            if path.suffix.lower() not in _SOURCE_EXTS:
                continue
            try:
                text = path.read_text(encoding="utf-8", errors="ignore")
            except OSError:
                continue
            lines = _code_lines(text)
            if lines <= 0:
                continue
            total += lines
            head = text[:800]
            if _AI_HEADER.search(head):
                ai += lines
        return total, ai

    def _scan_commits(self, root: Path) -> tuple[int, int]:
        if not have("git") or not (root / ".git").exists():
            return 0, 0

        res = run(
            ["git", "log", "--no-merges", "--format=COMMIT:%H%n%B", "--numstat"],
            cwd=str(root),
            timeout=120,
        )
        if not res.ok or not res.stdout.strip():
            return 0, 0

        total = ai = 0
        ai_commit = False
        for line in res.stdout.splitlines():
            if line.startswith("COMMIT:"):
                ai_commit = False
                continue
            parts = line.split("\t")
            if len(parts) == 3 and (parts[0].isdigit() or parts[0] == "-"):
                try:
                    added = int(parts[0]) if parts[0] != "-" else 0
                    deleted = int(parts[1]) if parts[1] != "-" else 0
                except ValueError:
                    continue
                changed = added + deleted
                if changed <= 0:
                    continue
                total += changed
                if ai_commit:
                    ai += changed
                continue
            if _AI_COMMIT.search(line):
                ai_commit = True

        return total, ai


def _code_lines(text: str) -> int:
    count = 0
    for line in text.splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#") and not stripped.startswith("//"):
            count += 1
    return count


def _walk(root: Path):
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d.lower() not in _SKIP_DIRS]
        for fn in filenames:
            yield Path(dirpath) / fn
