"""LOC, language, file-count and auto-generated metrics via scc.

One ``scc --by-file --format json`` pass per repo provides everything here; the JSON is
also cached on the collector so the code-analysis collector can reuse file lists.
"""

from __future__ import annotations

import fnmatch

from ..tools import have, run_json
from .base import Collector

# Directory + filename patterns the data dictionary lists as auto-generated, plus common
# native/compiler build-output dirs (Android NDK, CMake, Gradle) whose committed artifacts
# scc otherwise miscounts as source (e.g. *.o.d Make dependency files seen as "D").
GENERATED_DIR_PATTERNS = (
    "vendor", "node_modules", "dist", "build", "generated",
    "__generated__", "migrations", "obj", "objs", ".externalnativebuild",
    ".cxx", "cmake-build-debug", "cmake-build-release", "intermediates", ".gradle",
)
GENERATED_FILE_GLOBS = (
    "*_generated.*", "*_pb2.py", "*_pb2_grpc.py", "*.pb.go",
    "*.min.js", "*.min.css", "*.bundle.js", "*.o.d",
    "*.lock",  # yarn.lock, Cargo.lock, Gemfile.lock, poetry.lock, composer.lock, flake.lock…
)
# Lock/shrinkwrap files that don't end in `.lock` (those are covered by the glob above).
LOCK_FILES = {"package-lock.json", "pnpm-lock.yaml", "npm-shrinkwrap.json", "go.sum"}

# Markers found in the first lines of machine-written files (dictionary spec + common tools).
GENERATED_HEADER_MARKERS = (
    "do not edit", "code generated by", "auto-generated", "autogenerated",
    "@generated", "this file was generated", "generated by the protocol buffer",
    "machine generated", "automatically generated",
)

DEPENDENCY_DIRS = (
    "node_modules", "vendor", ".venv", "venv", "site-packages",
    "pods", "target", "bower_components",
)

# scc "languages" that are data/markup/prose, not source code. Excluded from LOC totals,
# Primary Language and Language Distribution (per the "code statements" definition).
DATA_LANGUAGES = {
    "CSV", "TSV", "Plain Text", "Markdown", "ReStructuredText", "AsciiDoc", "Org",
    "JSON", "JSON5", "YAML", "XML", "TOML", "INI", "SVG", "BibTeX", "gitignore",
    "Docker ignore", "License", "Properties File", "Gettext Catalog", "Bitbake",
}

# Extensions the dictionary counts as "source files" (broader than code languages —
# includes config/docs). Used only for Total Source Files.
SOURCE_EXTS = {
    "py", "js", "ts", "tsx", "jsx", "java", "go", "rs", "rb", "c", "cpp", "h", "hpp",
    "cs", "php", "swift", "kt", "scala", "sh", "yml", "yaml", "json", "toml", "xml",
    "html", "css", "sql", "md", "txt", "cfg", "ini",
}

# Mainstream languages we expect to see. Anything outside this with a non-trivial share
# triggers a "please verify" warning (cheap guard against extension misdetection).
COMMON_LANGUAGES = {
    "Python", "JavaScript", "TypeScript", "Java", "Kotlin", "Go", "Rust", "Ruby",
    "PHP", "C", "C++", "C#", "Swift", "Scala", "Objective-C", "Objective-C++", "Dart",
    "Shell", "BASH", "PowerShell", "Lua", "Perl", "R", "Groovy", "Elixir", "Erlang",
    "Haskell", "Clojure", "HTML", "CSS", "SASS", "SCSS", "Less", "SQL", "Vue", "Svelte",
    "CUDA", "Assembly", "Gradle", "Makefile", "Dockerfile", "Terraform", "HCL",
}

# Normalise scc language names: merge header pseudo-languages into their base language and
# map onto the dictionary's Primary Language vocabulary.
_LANG_ALIASES = {
    "C++ Header": "C++",
    "C Header": "C",
    "CUDA Header": "CUDA",
    "Objective-C++ Header": "Objective-C++",
    "Objective C": "Objective-C",
}


class LocCollector(Collector):
    name = "loc"

    def collect(self) -> dict[str, object]:
        if not have("scc"):
            self.warn("scc not installed; LOC metrics skipped")
            return {}

        per_lang_code: dict[str, int] = {}
        raw = code = autogen = files = 0
        self.file_records: list[dict] = []  # reused by code-analysis collector

        for repo in self.repos:
            data = run_json(["scc", "--by-file", "--format", "json", str(repo.path)])
            if data is None:
                self.warn(f"scc produced no output for {repo.name}")
                continue
            # Aggregate per file so generated/build artifacts can be filtered out of the
            # LOC totals and language stats (and counted toward Auto-Generated LOC instead).
            for lang in data:
                for f in lang.get("Files") or []:
                    self.file_records.append(f)
                    lang_name = f.get("Language") or lang["Name"]
                    is_data = lang_name in DATA_LANGUAGES
                    generated = self._is_generated(f, repo.path)

                    if (f.get("Extension") or "").lower() in SOURCE_EXTS and not generated:
                        files += 1

                    if generated:
                        if not is_data:
                            autogen += f["Code"]
                        continue
                    if is_data:
                        continue

                    raw += f["Lines"]
                    code += f["Code"]
                    name = _LANG_ALIASES.get(lang_name, lang_name)
                    per_lang_code[name] = per_lang_code.get(name, 0) + f["Code"]

        out: dict[str, object] = {
            "raw_loc": raw,
            "logical_loc": code,
            "autogen_loc": autogen,
            "total_source_files": files,
            "dependency_loc": self._dependency_loc(),
        }
        out.update(self._language_columns(per_lang_code))
        return out

    def _is_generated(self, f: dict, repo_root) -> bool:
        # Cheap signals first: scc's own flags, lock files, path + filename patterns.
        if f.get("Generated") or f.get("Minified"):
            return True
        location = f["Location"].replace("\\", "/").lower()
        filename = f["Filename"]
        if filename.lower() in LOCK_FILES:
            return True
        if set(location.split("/")) & {p.lower() for p in GENERATED_DIR_PATTERNS}:
            return True
        if any(fnmatch.fnmatch(filename.lower(), g) for g in GENERATED_FILE_GLOBS):
            return True
        # Content signal: a generated-by/DO-NOT-EDIT marker in the file's first lines.
        # This catches machine-written files regardless of extension or language.
        return self._has_generated_header(repo_root, f["Location"])

    @staticmethod
    def _has_generated_header(repo_root, location: str) -> bool:
        from pathlib import Path

        try:
            path = Path(repo_root) / location
            with path.open("r", encoding="utf-8", errors="ignore") as fh:
                head = "".join(next(fh, "") for _ in range(5)).lower()
        except OSError:
            return False
        return any(marker in head for marker in GENERATED_HEADER_MARKERS)

    def _dependency_loc(self) -> int | str:
        """LOC living inside dependency dirs (vendored or locally installed).

        Only counts dependency code that is actually present in the checkout. Most repos
        gitignore these dirs, so a fresh clone legitimately has none -> we report 0
        ("measured, none present"), not blank. Returns "" only if scc is unavailable.
        """
        if not have("scc"):
            return ""
        total = 0
        for repo in self.repos:
            for dep in DEPENDENCY_DIRS:
                target = repo.path / dep
                if not target.is_dir():
                    continue
                data = run_json(
                    ["scc", "--no-ignore", "--no-gitignore", "--format", "json", str(target)]
                )
                if data:
                    total += sum(
                        lang["Code"] for lang in data if lang["Name"] not in DATA_LANGUAGES
                    )
        return total

    def _language_columns(self, per_lang_code: dict[str, int]) -> dict[str, object]:
        total = sum(per_lang_code.values())
        if total == 0:
            return {"primary_language": "", "language_distribution": ""}
        ranked = sorted(per_lang_code.items(), key=lambda kv: kv[1], reverse=True)
        primary = ranked[0][0]
        dist = {
            lang: round(loc / total, 4)
            for lang, loc in ranked
            if loc / total >= 0.01  # dictionary: list languages >= 1%
        }
        # Safety net: flag uncommon languages with a meaningful share so a human can
        # sanity-check (an obscure language is often an extension misdetection).
        for lang, pct in dist.items():
            if lang not in COMMON_LANGUAGES and pct >= 0.05:
                self.warn(
                    f"uncommon language '{lang}' is {pct:.0%} of code — verify it is not "
                    "misdetected build output or vendored files"
                )
        return {"primary_language": primary, "language_distribution": _fmt_dist(dist)}


def _fmt_dist(dist: dict[str, float]) -> str:
    inner = ", ".join(f'"{lang}": {pct:.2f}' for lang, pct in dist.items())
    return "{" + inner + "}"
